name: Deploy to Vercel

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        cd client && npm install
        
    - name: Run linting
      run: |
        cd client && npm run build
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
